### PR TITLE
Docs improvement since module7

### PR DESCRIPTION
**Pull request by SignorMercurio**
This PR mainly includes docs improvement from module7 to module11.

### CODE REVIEW

**Comment by mfanjie** [comment]
@SignorMercurio could you please rebase, there conflict.

**Comment by SignorMercurio** [comment]
> @SignorMercurio could you please rebase, there are conflicts.

Thanks for reminding. I've merged the conflicts, could you please check if it's ok now?

**Comment by mfanjie** [comment]
@SignorMercurio sorry, it conflicts again.. could you please do again and notify me when you complete via wechat so I will do a immediate merge

**Comment by SignorMercurio** [comment]
Never mind, I've fixed it now :)

**Pull request merged**
